version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    user: 1000:1000
    group_add:
      - "109"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - /Storage/qxzero/jellyfin/config:/config
      - /Storage/qxzero/jellyfin/cache:/cache
      - /Storage/MEDIA:/media
    devices:
      # VAAPI Devices (examples)
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0