version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: always
    network_mode: host
    ports:
      - 3000:3000
    volumes:
      - /opt/qxzero/home/config:/app/config # Make sure your local config directory exists
      - /opt/qxzero/home/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations